### PR TITLE
Remove redux and refactor to mobx store and actions

### PR DESCRIPTION
**Pull request by darko-mijic**
Changes:
- Redux was removed
- MobX is running in strict mode
- `addBanker` and `removeBanker` actions are refactored to MobX actions:

``` javascript
import store from '../store';
import { action } from 'mobx';

export const addBanker = () => {
  return action('addBanker', () => {
    store.bankersCount++;
  });
};
```
- store is refactored to simple MobX observable state:

``` javascript
import { observable } from 'mobx';

export default store = observable({
  bankersCount: 1,
  allAccounts: [],
  allTransactions: []
});
```
- autoruns are using MobX actions to change the state:

``` javascript
import store from '../store';
import * as Collections from '../../infrastructure/collections';
import { Meteor } from 'meteor/meteor';
import { action } from 'mobx';

export default () => {

  // ALL BANK ACCOUNTS
  Meteor.subscribe('accounts');
  action('updateAccountsFromAutorun', (accounts) => {
    store.allAccounts = accounts;
  })(Collections.BankAccounts.find({}, {sort: {creationDate: 1}}).fetch());

};

```

### CODE REVIEW

**Comment by darko-mijic** [comment]
Actions that are sending commands could like this one:

``` javascript
import ClientApp from '../application';
import commands from '../../domain/commands';
import Contact from '../../domain/value-objects/contact';
import NIN from '../../domain/value-objects/nin';
import Chance from 'chance';

const { OpenBankAccount } = commands;

export const addBankAccount = () => {

  return dispatch => {

    const chance = new Chance();

    const command = new OpenBankAccount({
      targetId: new Guid(),
      owner: new Contact({
        name: chance.name(),
        email: new EmailAddress(chance.email()),
        nin: new NIN({
          nin: chance.ssn(),
          countryCode: chance.country()
        })
      }),
      initialBalance: new Money(chance.floating({min: 0, max: 100000}) ),
      overdraft: new Money(chance.floating({min: 10000, max: 10000}) ),
      currency: new Currency('EUR')
    });

    ClientApp.send(command);

  };

};
```

could also be MobX actions and mutate client side state for latency compensation. Thoughts @rhyslbw and @DominikGuzei?

**Comment by darko-mijic** [comment]
> Add .babelrc decorator class properties
> That's the plan @rhyslbw. I am working on ESLint configuration that will support that. Our standard configuration needs upgrades. Are you still using our current ESLint configuration?

**Comment by rhyslbw** [comment]
weird… body wasn't staged in the commit. I was just checking this in now for future evolution. The two packages to make this work are:
- `babel-plugin-transform-decorators-legacy`
- `babel-plugin-transform-class-properties`

**Comment by rhyslbw** [comment]
Pretty sure I've changed my ESLint. Let's store the next one in SC !

**Comment by darko-mijic** [comment]
Store can be simplified like this:

``` javascript
import { observable } from 'mobx';

export default observable({
  bankersCount: 1,
  allAccounts: [],
  allTransactions: []
});
```

It would be better to import it as state probably:
`import state from '../store';`

**Comment by rhyslbw** [comment]
Good start on the refactor @darko-mijic. I like this approach of decorating our own code (with or without the @ syntax). It also visualises that an autorun is just like any other user-generated action to MobX -> nice isolation with just a few LOC.

> … could also be MobX actions and mutate client side state for latency compensation. 

I was thinking about this yesterday 🎱. We just need to modify the projected collection in a method stub (`isSimulation`), optionally in a client side Space.messaging.Api, to achieve an nicely integrated sync with Mongo.Collection data. Might not be as optimal though, maybe do some performance tests

**Comment by darko-mijic** [comment]
> We just need to modify the projected collection in a method stub (isSimulation)

This will probably not be as performant as modifying MobX state directly for latency compensation. Client side collection will sync when autoruns fire with server-side collection state. 

> optionally in a client side Space.messaging.Api

👍

**Comment by darko-mijic** [comment]
There is one mayor issue with decorating autoruns with MobX actions. They do not invalidate and re-run when MobX state is updated. Eg `selectedItemId` which is updated with MobX action and than `selectedItemData` should be loaded for `selectedItemId`.

**Comment by darko-mijic** [comment]
There is an easy and clean fix for this. Autoruns should not be decorated with actions and rather use actions to update MobX state. Like this:

``` javascript
import state from '../store';
import * as Collections from '../../lib/collections';
import { Meteor } from 'meteor/meteor';
import { action } from 'mobx';

const updatePost = action('updatePostFromAutorun', (post) => {
  state.selectedPost = post;
});

export default () => {

  // SELECTED POST
  const postId = state.selectedPostId;
  Meteor.subscribe('posts.single', postId);
  updatePost(postId ? Collections.Posts.findOne(postId) : null);
}
```

**Comment by rhyslbw** [comment]
> ill probably not be as performant as modifying MobX state directly for latency compensation. 
> It's just the initial autorun that will add the extra latency since we're driving the UI from the store. A local test routing via MiniMongo vs updating the store directly might be the best way to see 😄 . 

But since all we're doing here is simulating change to a projection, I've often thought about simulating a domain event that is passed to the projection (on the client with environment-specific handling) instead, with the real domain event then correcting any invalid assumptions. 

Does MobX ignore attempts to update an observable with the same value such as a field in a MiniMongo doc?

**Comment by rhyslbw** [comment]
Agree. It's more logical anyway.

Could just inline that. Makes it more like an event bus 🚌  

``` javascript
export default () => {

  // SELECTED POST
  const postId = state.selectedPostId;
  Meteor.subscribe('posts.single');
  action(…)

}
```

**Comment by rhyslbw** [comment]
Should also be using the subscription handle to query the collection in the `onReady` callback

**Comment by darko-mijic** [comment]
> Should also be using the subscription handle to query the collection in the onReady callback

👍 
Yes, thanks for the note. I am planing to do that and manage loading state.

**Comment by darko-mijic** [comment]
> Does MobX ignore attempts to update an observable with the same value such as a field in a MiniMongo doc?

I will check if the update happens or not. But I am sure that there are no side effects if values stays the same. Eg. observer will re-render only decorated components that are effected (components that use modified peace of state). This is why it is important to decorate with observer complete hierarchy of React components that depend on MobX managed state.

**Comment by darko-mijic** [comment]
@DominikGuzei: Take a look what Rhys and me did here. Summary of the changes is in the description, key thins are: redux has been removed are MobX is running in strict mode so we are using MobX actions to change the MobX managed state.

**Pull request merged**
