### PR TITLE
Redux router

### PR DESCRIPTION
**Pull request by darko-mijic**

### CODE REVIEW

**Comment by darko-mijic** [comment]
@meteor-space/core please review this proposition to replace flow router with `react-router` and `react-router-redux` on top. `redux-thunk` middleware is also new here so we have  nice `redux-logger` and router middleware with browsing history.

**Comment by DominikGuzei** [comment]
Ok have several thoughts:
1. Main reason for FlowRouter is simple API + possibility of Server Side Rendering (we really need to support that with Space)
2. The react-router markup looks horrible, components for routing? wtf
3. Why do we need a login for this example? :laughing: it should be a tech demo for projection rebuilding

**Comment by darko-mijic** [comment]
The main reason for react router is having `react-router-redux`: 
https://github.com/reactjs/react-router-redux
which gives us some nice features like restoring the state of redux store from browser history, ability to go back to previous app state...

https://github.com/meteor-space/projection-rebuilding-example/blob/chore/replace-flow-router-with-redux-router/source/imports/ui/store.js#l10
- push - Pushes a new location to history, becoming the current location.
- replace - Replaces the current location in history.
- go - Moves backwards or forwards a relative number of locations in history.
- goForward - Moves forward one location. Equivalent to go(1)
- goBack - Moves backwards one location. Equivalent to go(-1)

**Comment by DominikGuzei** [comment]
Sounds great on paper, do you have any real world use case for it? :)
You can do all of that with FlowRouter too, those are standard routing features, nothing special.
Maybe im missing something, but i don't see the big feature here?

**Comment by darko-mijic** [comment]
It is possible to have server side rendering with this setup. 

Real world example: you log in to the app and pick up where you left of :) I will make another PR with flow router and we can discuss later this week before i build start building the actual features. ;)

**Comment by DominikGuzei** [comment]
Ok great, so i just want to keep the focus on our goals with this example :wink:
So im not even sure if we need routing here at all! it's just a simple page with some options to checkout projection rebuilding IMO.

**Comment by rhyslbw** [comment]
I agree, at least for now. Let's focus on the ability to use the app to do a real world testing with the improved rebuilding functionality, as that is very pressing since right now there's a limit on how big the store can be before things fall over during a rebuild

**Comment by darko-mijic** [comment]
We have two goals with this app, right?
1. demonstration of projection rebuilding since it is our prime feature
2. full stack space infrastructure wired up with es6 modules

**Comment by DominikGuzei** [comment]
from my point it's mostly the first goal, the second one was just a happy side-effect but i would like to keep this example focussed on the projection rebuilding demo / critical test for us. So we could drop routing and definitely need no login etc. for now.

**Pull request closed without merging**
